version: "3.5"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - mdcp_panel_db:/var/lib/postgresql/data
    networks:
      - mdcp_panel_net

  web:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py test &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - mdcp_panel_static:/code/staticfiles
    networks:
      - mdcp_panel_net
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    restart: always
    build:
      context: ./nginx/
    ports:
      - "7979:8080"
    networks:
      - mdcp_panel_net
    depends_on:
      - web
    volumes:
      - mdcp_panel_static:/www/static

volumes:
  mdcp_panel_db: {}
  mdcp_panel_static: {}

networks:
  mdcp_panel_net: {}
