# Generated by Django 3.1.4 on 2020-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jarfile', models.FileField(upload_to='jarfiles/%Y/%m/%d')),
            ],
        ),
    ]
