# Generated by Django 3.1.4 on 2021-01-02 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('executable', models.FileField(upload_to='jobs/%Y/%m/%d/executables/')),
                ('input_file', models.FileField(upload_to='jobs/%Y/%m/%d/input_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPartialResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('partial_result_file', models.FileField(upload_to='jobs/%Y/%m/%d/result_files/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.job')),
            ],
        ),
    ]
