# Generated by Django 3.1.5 on 2021-01-07 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 1, 22, 4, 3525), editable=False),
        ),
        migrations.AddField(
            model_name='jobpartialresult',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 1, 22, 4, 4035), editable=False),
        ),
    ]
