# Generated by Django 3.1.5 on 2021-01-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20210108_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpartialresult',
            name='consumed_time',
            field=models.IntegerField(default=-1),
        ),
    ]
