# Generated by Django 3.1.7 on 2021-02-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_jobpartialresult_consumed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='final_result_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='outputs_merger',
            field=models.FileField(null=True, upload_to='jobs/%Y/%m/%d/outputs_mergers/'),
        ),
    ]
